### ISSUE TITLE
OneFS 9 / PowerScale Support

### ISSUE THREAD

**Issue by eschek87** [Isilon/isilon_data_insights_connector#110]
Currently it isn't working. I have installed the sdk for 9.0 release

/usr/bin/python /opt/isilon_data_insights_connector-master/isi_data_insights_d.py start -c /opt/isilon_data_insights_connector-master/isi_data_insights_d.cfg -p /opt/isilon_data_insights_connector-master/isi_data_insights_d.pid -l /opt/isilon_data_insights_connector-master/isi_data_insights_d.log
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
Configured 10.20.11.152 as version 8 cluster, using SDK isi_sdk_8_0.
Configured 10.20.11.202 as version 8 cluster, using SDK isi_sdk_8_0.
Computing update intervals for stat group: cluster_cpu_stats.
Computing update intervals for stat group: cluster_network_traffic_stats.
Computing update intervals for stat group: cluster_client_activity_stats.
Computing update intervals for stat group: cluster_health_stats.
Computing update intervals for stat group: ifs_space_stats.
Computing update intervals for stat group: ifs_rate_stats.
Computing update intervals for stat group: node_load_stats.
Traceback (most recent call last):
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_d.py", line 65, in <module>
    main()
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 668, in configure_via_file
    config_file, stat_group, global_cluster_list)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 345, in _configure_stat_groups_via_file
    update_intervals)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 243, in _compute_stat_group_update_intervals
    if stat_metadata.default_cache_time:
AttributeError: 'NoneType' object has no attribute 'default_cache_time'

**Comment by eschek87** [comment]
Seems to work with the latest version available here, just needed to comment "node.memory.cache" out. Which seems not to be suppoted.
