### ISSUE TITLE
Resolved. Help Please!  InfluxDB 2 is not supported.  I had to use 1.8

### ISSUE THREAD

**Issue by ofsthus** [Isilon/isilon_data_insights_connector#111]
I've been working on trying to get this to run....

Here is the Error I'm getting.  It doesnt seem to be able to create anything in FluxDB. 

  (.venv3) storauto@hpstgvlp024:/apps/isilon_data_insights_connector-master $ ./isi_data_insights_d.py start
InfluxDB username: admin
Password: 
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 78, in <module>
    main()
  File "./isi_data_insights_d.py", line 55, in main
    configure_via_file(daemon, args, config_file)
  File "/apps/isilon_data_insights_connector-master/isi_data_insights_config.py", line 671, in configure_via_file
    _configure_stats_processor(daemon, args.stats_processor, args.processor_args)
  File "/apps/isilon_data_insights_connector-master/isi_data_insights_config.py", line 602, in _configure_stats_processor
    daemon.set_stats_processor(processor, arg_list)
  File "/apps/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 472, in set_stats_processor
    self._stats_processor.start(self._stats_processor_args)
  File "/apps/isilon_data_insights_connector-master/influxdb_plugin.py", line 102, in start
    g_client.create_database(influxdb_name)
  File "/apps/isilon_data_insights_connector-master/.venv3/lib64/python3.6/site-packages/influxdb/client.py", line 747, in create_database
    method="POST")
  File "/apps/isilon_data_insights_connector-master/.venv3/lib64/python3.6/site-packages/influxdb/client.py", line 539, in query
    in data.get('results', [])
  File "/apps/isilon_data_insights_connector-master/.venv3/lib64/python3.6/site-packages/influxdb/client.py", line 538, in <listcomp>
    for result
  File "/apps/isilon_data_insights_connector-master/.venv3/lib64/python3.6/site-packages/influxdb/resultset.py", line 25, in __init__
    raise InfluxDBClientError(self.error)
influxdb.exceptions.InfluxDBClientError: not implemented: CREATE DATABASE

**Comment by tenortim** [comment]
Sorry, yes, 2.x is incompatible. I'm looking at what it would take to support but it's non-trivial.
I will update the documentation at least to make it clear.

**Comment by tenortim** [comment]
Closing in deference to #106
