### ISSUE TITLE
Deamon terminates when cluster is not responding due to network timeout

### ISSUE THREAD

**Issue by pondi** [Isilon/isilon_data_insights_connector#23]
Hi guys,

Struggle a bit with the deamon when one of our clusters gets "unresponsive" due to network or system maintenance. We have a lot of clusters cross several sites and this happens from time to time. Deamon  stops/terminates and needs to get started.

Snippet from logs are below and I suspect that an try/expection for the .get() request in  isi_stat_client.py -> the query_stat() function is missing  when timeout have happned past retry times.

I have worked very little with Python and was hoping some of you guys could have a look at this?

```
2017-03-01 14:45:54,145:urllib3.connectionpool:WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b12b6c21
0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.open.files%2Ccluster.protostats.siq.total%2Cnode.clientstats.conn
ected.ftp%2Ccluster.net.ext.bytes.out.rate%2Cnode.clientstats.active.smb2%2Ccluster.net.ext.errors.in.rate%2Ccluster.protostats.irp.total%2Cifs.ops.out.rate%2Cnode.clientstats.connected.cifs%2Ccluster.cpu.idle.avg%2Ccluster.net.ext.packe
ts.out.rate%2Cnode.ifs.heat.rename.total%2Cifs.bytes.out.rate%2Ccluster.protostats.irp%2Cnode.load.5min%2Cnode.memory.used%2Ccluster.protostats.nlm.total%2Cnode.clientstats.active.hdfs%2Cnode.clientstats.connected.nlm%2Ccluster.protostat
s.nfs4.total%2Ccluster.protostats.nlm%2Cnode.ifs.heat.read.total%2Cnode.clientstats.active.nlm%2Ccluster.health%2Ccluster.disk.bytes.out.rate%2Ccluster.disk.bytes.in.rate%2Ccluster.protostats.nfs%2Ccluster.protostats.papi.total%2Ccluster
.node.count.all%2Ccluster.protostats.smb2.total%2Ccluster.protostats.jobd%2Ccluster.net.ext.packets.in.rate%2Ccluster.protostats.lsass_out%2Ccluster.protostats.hdfs.total%2Cnode.clientstats.connected.hdfs%2Ccluster.protostats.lsass_in%2C
node.clientstats.active.nfs4%2Cnode.clientstats.active.ftp%2Cnode.ifs.heat.deadlocked.total%2Ccluster.protostats.nfs4%2Cnode.clientstats.connected.papi%2Cnode.ifs.cache%2Ccluster.protostats.lsass_in.total%2Cnode.ifs.heat.lock.total%2Cclu
ster.net.ext.errors.out.rate%2Cnode.clientstats.connected.siq%2Cnode.clientstats.active.lsass_out%2Cifs.ops.in.rate%2Cnode.clientstats.active.cifs%2Cnode.ifs.heat.link.total%2Cnode.ifs.heat.setattr.total%2Cnode.load.15min%2Ccluster.proto
stats.cifs%2Cnode.clientstats.active.nfs%2Ccluster.net.ext.bytes.in.rate%2Ccluster.protostats.nfs.total%2Cnode.ifs.heat.getattr.total%2Cnode.ifs.heat.unlink.total%2Ccluster.protostats.http%2Cnode.ifs.heat.blocked.total%2Cnode.clientstats
.active.jobd%2Ccluster.protostats.hdfs%2Ccluster.protostats.cifs.total%2Ccluster.protostats.ftp%2Cnode.clientstats.active.http%2Cnode.load.1min%2Ccluster.node.count.down%2Ccluster.cpu.intr.avg%2Cnode.ifs.heat.write.total%2Ccluster.disk.x
fers.in.rate%2Cnode.memory.cache%2Ccluster.cpu.user.avg%2Ccluster.disk.xfers.out.rate%2Ccluster.protostats.http.total%2Ccluster.disk.xfers.rate%2Cnode.clientstats.active.siq%2Ccluster.protostats.siq%2Ccluster.protostats.ftp.total%2Cclust
er.cpu.sys.avg%2Cnode.ifs.heat.contended.total%2Ccluster.protostats.jobd.total%2Cnode.cpu.throttling%2Ccluster.protostats.smb2%2Cnode.clientstats.active.papi%2Cnode.clientstats.connected.http%2Cifs.bytes.in.rate%2Cnode.clientstats.connec
ted.nfs%2Ccluster.protostats.papi%2Cnode.memory.free%2Cnode.ifs.heat.lookup.total&devid=all&substr=False&timeout=60&degraded=True&expand_clientid=False
2017-03-01 14:45:54,170:daemons.startstop.simple:ERROR: Uncaught exception in the daemon run() method.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/daemons/startstop/simple.py", line 43, in start
    self.run()
  File "/home/grafana/isi_data_insights_daemon.py", line 148, in run
    self._query_and_process_stats(time.time())
  File "/home/grafana/isi_data_insights_daemon.py", line 215, in _query_and_process_stats
    results = stats_client.query_stats(stats)
  File "/home/grafana/isi_stats_client.py", line 80, in query_stats
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/apis/statistics_api.py", line 139, in get_statistics_current
    callback=params.get('callback'))
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/api_client.py", line 339, in call_api
    response_type, auth_settings, callback)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/api_client.py", line 166, in __call_api
    post_params=post_params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/api_client.py", line 359, in request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/rest.py", line 184, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/rest.py", line 161, in request
    headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 69, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 90, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 162, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 630, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='nas01', port=8080): Max retries exceeded with url: /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.open.files%2Ccluster.protostats.siq.total%2Cnode.clientstats.conn
ected.ftp%2Ccluster.net.ext.bytes.out.rate%2Cnode.clientstats.active.smb2%2Ccluster.net.ext.errors.in.rate%2Ccluster.protostats.irp.total%2Cifs.ops.out.rate%2Cnode.clientstats.connected.cifs%2Ccluster.cpu.idle.avg%2Ccluster.net.ext.packe
ts.out.rate%2Cnode.ifs.heat.rename.total%2Cifs.bytes.out.rate%2Ccluster.protostats.irp%2Cnode.load.5min%2Cnode.memory.used%2Ccluster.protostats.nlm.total%2Cnode.clientstats.active.hdfs%2Cnode.clientstats.connected.nlm%2Ccluster.protostat
s.nfs4.total%2Ccluster.protostats.nlm%2Cnode.ifs.heat.read.total%2Cnode.clientstats.active.nlm%2Ccluster.health%2Ccluster.disk.bytes.out.rate%2Ccluster.disk.bytes.in.rate%2Ccluster.protostats.nfs%2Ccluster.protostats.papi.total%2Ccluster
.node.count.all%2Ccluster.protostats.smb2.total%2Ccluster.protostats.jobd%2Ccluster.net.ext.packets.in.rate%2Ccluster.protostats.lsass_out%2Ccluster.protostats.hdfs.total%2Cnode.clientstats.connected.hdfs%2Ccluster.protostats.lsass_in%2C
node.clientstats.active.nfs4%2Cnode.clientstats.active.ftp%2Cnode.ifs.heat.deadlocked.total%2Ccluster.protostats.nfs4%2Cnode.clientstats.connected.papi%2Cnode.ifs.cache%2Ccluster.protostats.lsass_in.total%2Cnode.ifs.heat.lock.total%2Cclu
ster.net.ext.errors.out.rate%2Cnode.clientstats.connected.siq%2Cnode.clientstats.active.lsass_out%2Cifs.ops.in.rate%2Cnode.clientstats.active.cifs%2Cnode.ifs.heat.link.total%2Cnode.ifs.heat.setattr.total%2Cnode.load.15min%2Ccluster.proto
stats.cifs%2Cnode.clientstats.active.nfs%2Ccluster.net.ext.bytes.in.rate%2Ccluster.protostats.nfs.total%2Cnode.ifs.heat.getattr.total%2Cnode.ifs.heat.unlink.total%2Ccluster.protostats.http%2Cnode.ifs.heat.blocked.total%2Cnode.clientstats
.active.jobd%2Ccluster.protostats.hdfs%2Ccluster.protostats.cifs.total%2Ccluster.protostats.ftp%2Cnode.clientstats.active.http%2Cnode.load.1min%2Ccluster.node.count.down%2Ccluster.cpu.intr.avg%2Cnode.ifs.heat.write.total%2Ccluster.disk.xfers.in.rate%2Cnode.memory.cache%2Ccluster.cpu.user.avg%2Ccluster.disk.xfers.out.rate%2Ccluster.protostats.http.total%2Ccluster.disk.xfers.rate%2Cnode.clientstats.active.siq%2Ccluster.protostats.siq%2Ccluster.protostats.ftp.total%2Ccluster.cpu.sys.avg%2Cnode.ifs.heat.contended.total%2Ccluster.protostats.jobd.total%2Cnode.cpu.throttling%2Ccluster.protostats.smb2%2Cnode.clientstats.active.papi%2Cnode.clientstats.connected.http%2Cifs.bytes.in.rate%2Cnode.clientstats.connected.nfs%2Ccluster.protostats.papi%2Cnode.memory.free%2Cnode.ifs.heat.lookup.total&devid=all&substr=False&timeout=60&degraded=True&expand_clientid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0b12b6c5d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
2017-03-01 14:45:54,277:isi_data_insights_daemon:INFO: Stoppping.
```

**Comment by apecoraro** [comment]
I'll take a look at it. Thanks for letting us know.

**Comment by apecoraro** [comment]
Are you using the latest code? I'm wondering because as best as I can tell a MaxRetryError should be handled by this exception handling logic:
https://github.com/Isilon/isilon_data_insights_connector/blame/master/isi_data_insights_daemon.py#L222
The exception handling code was added about 6 months ago.

**Comment by pondi** [comment]
We are on the commit from 14. january this year.

On the last error in the log it states "No address associated with hostname". I would think that DNS could not resolve the IP for our cluster (since the cluster is not responding to DNS queries when the network connection is bad between locations).

The urllib3.exceptions.HTTPError will only catch HTTP based error codes if it gets a reponse and not an error related to network.

The exception in my error is urllib3.exceptions.NewConnectionError, should this be implemented somewhere? It bases urlib3.exceptions.ConnectTimeoutError and is thrown when a new connection could not be established (according to documentation).

Sorry if I guided you on the wrong track when i said it was related to timeouts!

**Comment by apecoraro** [comment]
Maybe it has to do with the version of urllib3 that you are using? I'm using 1.18 according to pip:

$ pip show urllib3
...
Name: urllib3
Version: 1.18
...

In the version that I'm using NewConnectionError is a sub-class of ConnectTimeoutError which is a sub-class of TimeoutError which is a sub-class of HTTPError. So if it throws that then it should be handled without a crash. But if you have a different version of urllib3 that has a different inheritance tree then it would get past the exception handling logic.

When I try to simulate the issue you are having I see the same exceptions being thrown, but the daemon handles them without crashing, here's my log:

2017-03-16 17:12:49,302 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2fef291d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /platform/1/statistics/current?degraded=True&devid=all&key=cluster.protostats.lsass_out.total&timeout=60&expand_clientid=False
2017-03-16 17:12:49,302 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2fef291d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /platform/1/statistics/current?degraded=True&devid=all&key=cluster.protostats.lsass_out.total&timeout=60&expand_clientid=False
... <the above message repeats about 10 times until finally it runs out of retries>
2017-03-16 17:12:49,324:isi_data_insights_daemon:ERROR: Failed to query stats from cluster CSE-X200-2, exception raised: HTTPSConnectionPool(host='x200', port=8080): Max retries exceeded with url: /platform/1/statistics/current?degraded=True&devid=all&key=cluster.protostats.lsass_out.total&timeout=60&expand_clientid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd2fecea590>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by pondi** [comment]
I did an upgrade of urllib3 and your code base to the latest, but the issue is the same (I'm on 1.20 now).

The issue is with DNS resolvement and not directly with the network beeing unreachable. Since the hostname address is pointing to an delegated (NS) DNS record where the Isilon must response, when the cluster is having a network drop or something between locations, the DNS resolvement does not complete.

You can replicate this issue easily by using DNS against your ISI cluster and on the linux server where your daemon is running, just uncomment your DNS servers in /etc/resolv.conf
The deamon should hopefully crash the same way my does. At least I am able to replicate this each time.

I have gone through urllib3 and it seems they have not implemented a proper exception for "dns not responding" in their code. They have a pull request here that have not been implemented yet https://github.com/shazow/urllib3/pull/1008

I forked the project and did a fix that solved it for me This just checks to see if DNS resolves before querying the cluster. https://github.com/pondi/isilon_data_insights_connector/commit/22615ebbdd17384038549ba0fc6c08077f7ba2d2

I can create a pull request upstream if you want. I have no other idea on how to solve this so if you have any better ways it would be much appriciated.

**Comment by pondi** [comment]
I'm having an hmm-day today aswell.

I tried a generalized exception and that works. The daemon does not crash in my end. 
I first get a couple of warnings from the urlib3.connectionpool (only pasted in one of them below) before I straigth after get an ERROR with the exception "HTTPSConnectionPool".
.....
2017-03-20 09:13:41,919:urllib3.connectionpool:WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8a2bc5b90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /platform/1/statistics/current?keys=cluster.proto....rue&expand_clientid=False
.....
2017-03-20 09:13:41,920:isi_data_insights_daemon:ERROR: Failed to query stats from cluster isilon, exception raised: HTTPSConnectionPool(host='isilon', port=8080): Max retries exceeded with url: /platform/1/statistics/curren........and_clientid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8a2bc5d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

I get Errorno -3 here, don't know why I cannot replicate -5, but I think this has to do with where in the network stack the DNS error occurs. I am though on thin ice here. I don't have a test environment to test your setup where you removed the NS record from DNS. This would be to messy to do as a test in our prod env.

I think I have gotten out the debug code of what happnes when the deamon crashes. The following is thrown:

Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 57, in <module>
    main()
  File "./isi_data_insights_d.py", line 47, in main
    daemon.run()
  File "/home/grafana/isi_data_insights_daemon.py", line 148, in run
    self._query_and_process_stats(time.time())
  File "/home/grafana/isi_data_insights_daemon.py", line 215, in _query_and_process_stats
    results = stats_client.query_stats(stats)
  File "/home/grafana/isi_stats_client.py", line 80, in query_stats
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/apis/statistics_api.py", line 139, in get_statistics_current
    callback=params.get('callback'))
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/api_client.py", line 339, in call_api
    response_type, auth_settings, callback)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/api_client.py", line 166, in __call_api
    post_params=post_params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/api_client.py", line 359, in request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/rest.py", line 184, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/isi_sdk_8_0/rest.py", line 161, in request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nas', port=8080): Max retries exceeded with url: /platform/1/statistics/current...entid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f928ee61f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

And from this it seems like urllib3 are not handling issues with DNS resolvement as part of their exception module. 

I don't know where to go from here. I updated my fork with changes to the exception handler aswell. At least that works for us until an exception is implemented into urllib3 (if that is the root cause, at least it seems to be).

Do you want me to open an issue with that project or shall we just wait until they have implemented that pull request they have pending that seems to address name resolution?

**Comment by apecoraro** [comment]
I think the correct way to fix this is to identify the exact type of exception that is being thrown and add that to the list of exceptions that are handled by the daemon when requesting stats from the cluster.

So can you switch back to a general exception handler on line 223 of isi_data_insights_daemon.py, but add another line to print out the type of the exception. So it should look like this:

```python
        except Exception as http_exc:
            print "Exception Type=%s" % str(type(http_exc))
```

Then post the output of that.

Once we know the exact type of the exception that is being thrown then we should be able to add it to the two that are currently handled (urllib3.exceptions.HTTPError and cluster.isi_sdk.rest.ApiException).

Thanks.

**Comment by pondi** [comment]
I reverted back to master and changed the exception to the more generalized one and added the printout.
Code looks like below, no other changes have been made to make no confusion.

```python
            except Exception as http_exc:
                LOG.error("Failed to query stats from cluster %s, exception "\
                          "raised: %s", cluster.name, str(http_exc))
                print "Exception Type=%s" % str(type(http_exc))
                continue
```

The error I get is printed out below (running the deamon in with the debug parameter).

2017-03-23 09:09:29,312:isi_data_insights_daemon:ERROR: Failed to query stats from cluster isilon08, exception raised: HTTPSConnectionPool(host='isilon08', port=8080): Max retries exceeded with url: /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.o.........True&expand_clientid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fad3e4c0f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Exception Type=<class 'urllib3.exceptions.MaxRetryError'>

Only exception I can get out of this is the same traceback/error exception i get in my comment above, urllib3.exceptions.MaxRetryError. 
This is right before the demon enters the stopped state and the error output is the same regardless if i have the generalized Exception or the specific one.

Only I can see is that tje following is thrown as part of the error message from the exception, "Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at".

Are you sure we are not looking at a bug in urllib3 where something does not have an exception handler?

**Comment by apecoraro** [comment]
So are you saying that even with the code like this:

```python
            except Exception as http_exc:
                LOG.error("Failed to query stats from cluster %s, exception "\
                          "raised: %s", cluster.name, str(http_exc))
                print "Exception Type=%s" % str(type(http_exc))
                continue
```

the daemon still exits right after you see the error message below in the log/debug output?

2017-03-23 09:09:29,312:isi_data_insights_daemon:ERROR: Failed to query stats from cluster isilon08, exception raised: HTTPSConnectionPool(host='isilon08', port=8080): Max retries exceeded with url: /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.o.........True&expand_clientid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fad3e4c0f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Exception Type=<class 'urllib3.exceptions.MaxRetryError'>

Are there any other error messages in the log before or after you see the error message above? If that is the case, please cut and paste the entire log before and after the crash.

>> Are you sure we are not looking at a bug in urllib3 where something does not have an exception handler?

There might be a bug in urllib3 where it does not have an exception handler where it should, but even if that is the case the daemon should be able to work around that bug and continue running when that exception is incorrectly allowed to escape from urllib3 by handling the exception on its own.

Thanks.

**Comment by apecoraro** [comment]
Fixed this issue via commit: https://github.com/Isilon/isilon_data_insights_connector/commit/f3b75a8fdea695f374b53486f6c977826ddfe8b4
