### ISSUE TITLE
daemon starts and crashes after one minute.

### ISSUE THREAD

**Issue by lbanz** [Isilon/isilon_data_insights_connector#26]
`[root@onefsgrafana isilon_data_insights_connector]# grep -A150 16:46:46,205 isi_data_insights_d.log 
2017-05-01 16:46:46,205:daemons.startstop.simple:INFO: Succesfully stopped the process.
2017-05-01 16:46:46,219:daemons.daemonize.simple:INFO: Succesfully daemonized process 6282.
2017-05-01 16:46:46,219:daemons.startstop.simple:INFO: Beginning run loop for process.
2017-05-01 16:46:46,220:isi_data_insights_daemon:INFO: Starting.
2017-05-01 16:47:47,085:urllib3.connectionpool:WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x4835690>: Failed to establish a new connection: [Errno 111] Connection refused',)': /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.open.files%2Ccluster.protostats.siq.total%2Cnode.clientstats.connected.ftp%2Ccluster.net.ext.bytes.out.rate%2Cnode.clientstats.active.smb1%2Cnode.clientstats.active.smb2%2Ccluster.net.ext.errors.in.rate%2Ccluster.protostats.irp.total%2Cifs.ops.out.rate%2Cnode.clientstats.connected.cifs%2Ccluster.cpu.idle.avg%2Ccluster.net.ext.packets.out.rate%2Cnode.ifs.heat.rename.total%2Cifs.bytes.out.rate%2Ccluster.protostats.irp%2Cnode.load.5min%2Cnode.memory.used%2Ccluster.protostats.nlm.total%2Cnode.clientstats.active.hdfs%2Cnode.clientstats.connected.nlm%2Cifs.bytes.free%2Ccluster.protostats.nfs4.total%2Cifs.percent.free%2Ccluster.protostats.nlm%2Cnode.ifs.heat.read.total%2Cnode.clientstats.active.nlm%2Ccluster.health%2Ccluster.disk.bytes.out.rate%2Ccluster.disk.bytes.in.rate%2Ccluster.protostats.nfs%2Ccluster.protostats.papi.total%2Cifs.bytes.used%2Ccluster.node.count.all%2Ccluster.protostats.smb2.total%2Ccluster.protostats.jobd%2Ccluster.net.ext.packets.in.rate%2Ccluster.protostats.lsass_out%2Ccluster.protostats.hdfs.total%2Cnode.clientstats.connected.hdfs%2Cnode.clientstats.active.nfs3%2Ccluster.protostats.lsass_in%2Cnode.clientstats.active.nfs4%2Cnode.clientstats.active.ftp%2Cnode.ifs.heat.deadlocked.total%2Ccluster.protostats.nfs4%2Cnode.clientstats.connected.papi%2Cnode.ifs.cache%2Ccluster.protostats.lsass_in.total%2Cifs.bytes.total%2Cnode.ifs.heat.lock.total%2Ccluster.net.ext.errors.out.rate%2Cnode.clientstats.connected.siq%2Cnode.clientstats.active.lsass_out%2Cifs.ops.in.rate%2Cnode.clientstats.active.cifs%2Cnode.ifs.heat.link.total%2Cnode.ifs.heat.setattr.total%2Cnode.load.15min%2Ccluster.protostats.cifs%2Cifs.percent.avail%2Ccluster.net.ext.bytes.in.rate%2Ccluster.protostats.nfs.total%2Cnode.ifs.heat.getattr.total%2Cnode.ifs.heat.unlink.total%2Ccluster.protostats.http%2Cnode.ifs.heat.blocked.total%2Cnode.clientstats.active.jobd%2Ccluster.protostats.hdfs%2Ccluster.protostats.cifs.total%2Ccluster.protostats.ftp%2Cnode.clientstats.active.http%2Cnode.load.1min%2Ccluster.node.count.down%2Ccluster.cpu.intr.avg%2Cifs.percent.used%2Cnode.ifs.heat.write.total%2Ccluster.disk.xfers.in.rate%2Cifs.bytes.avail%2Cnode.memory.cache%2Ccluster.cpu.user.avg%2Ccluster.disk.xfers.out.rate%2Ccluster.protostats.http.total%2Ccluster.disk.xfers.rate%2Cnode.clientstats.active.siq%2Ccluster.protostats.siq%2Ccluster.protostats.ftp.total%2Ccluster.cpu.sys.avg%2Cnode.ifs.heat.contended.total%2Ccluster.protostats.jobd.total%2Cnode.cpu.throttling%2Ccluster.protostats.smb2%2Cnode.clientstats.active.papi%2Cnode.clientstats.connected.http%2Cifs.bytes.in.rate%2Cnode.clientstats.connected.nfs%2Ccluster.protostats.papi%2Cnode.memory.free%2Cnode.ifs.heat.lookup.total&devid=all&substr=False&timeout=60&degraded=True&expand_clientid=False
2017-05-01 16:47:47,086:urllib3.connectionpool:WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x4cfe890>: Failed to establish a new connection: [Errno 111] Connection refused',)': /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.open.files%2Ccluster.protostats.siq.total%2Cnode.clientstats.connected.ftp%2Ccluster.net.ext.bytes.out.rate%2Cnode.clientstats.active.smb1%2Cnode.clientstats.active.smb2%2Ccluster.net.ext.errors.in.rate%2Ccluster.protostats.irp.total%2Cifs.ops.out.rate%2Cnode.clientstats.connected.cifs%2Ccluster.cpu.idle.avg%2Ccluster.net.ext.packets.out.rate%2Cnode.ifs.heat.rename.total%2Cifs.bytes.out.rate%2Ccluster.protostats.irp%2Cnode.load.5min%2Cnode.memory.used%2Ccluster.protostats.nlm.total%2Cnode.clientstats.active.hdfs%2Cnode.clientstats.connected.nlm%2Cifs.bytes.free%2Ccluster.protostats.nfs4.total%2Cifs.percent.free%2Ccluster.protostats.nlm%2Cnode.ifs.heat.read.total%2Cnode.clientstats.active.nlm%2Ccluster.health%2Ccluster.disk.bytes.out.rate%2Ccluster.disk.bytes.in.rate%2Ccluster.protostats.nfs%2Ccluster.protostats.papi.total%2Cifs.bytes.used%2Ccluster.node.count.all%2Ccluster.protostats.smb2.total%2Ccluster.protostats.jobd%2Ccluster.net.ext.packets.in.rate%2Ccluster.protostats.lsass_out%2Ccluster.protostats.hdfs.total%2Cnode.clientstats.connected.hdfs%2Cnode.clientstats.active.nfs3%2Ccluster.protostats.lsass_in%2Cnode.clientstats.active.nfs4%2Cnode.clientstats.active.ftp%2Cnode.ifs.heat.deadlocked.total%2Ccluster.protostats.nfs4%2Cnode.clientstats.connected.papi%2Cnode.ifs.cache%2Ccluster.protostats.lsass_in.total%2Cifs.bytes.total%2Cnode.ifs.heat.lock.total%2Ccluster.net.ext.errors.out.rate%2Cnode.clientstats.connected.siq%2Cnode.clientstats.active.lsass_out%2Cifs.ops.in.rate%2Cnode.clientstats.active.cifs%2Cnode.ifs.heat.link.total%2Cnode.ifs.heat.setattr.total%2Cnode.load.15min%2Ccluster.protostats.cifs%2Cifs.percent.avail%2Ccluster.net.ext.bytes.in.rate%2Ccluster.protostats.nfs.total%2Cnode.ifs.heat.getattr.total%2Cnode.ifs.heat.unlink.total%2Ccluster.protostats.http%2Cnode.ifs.heat.blocked.total%2Cnode.clientstats.active.jobd%2Ccluster.protostats.hdfs%2Ccluster.protostats.cifs.total%2Ccluster.protostats.ftp%2Cnode.clientstats.active.http%2Cnode.load.1min%2Ccluster.node.count.down%2Ccluster.cpu.intr.avg%2Cifs.percent.used%2Cnode.ifs.heat.write.total%2Ccluster.disk.xfers.in.rate%2Cifs.bytes.avail%2Cnode.memory.cache%2Ccluster.cpu.user.avg%2Ccluster.disk.xfers.out.rate%2Ccluster.protostats.http.total%2Ccluster.disk.xfers.rate%2Cnode.clientstats.active.siq%2Ccluster.protostats.siq%2Ccluster.protostats.ftp.total%2Ccluster.cpu.sys.avg%2Cnode.ifs.heat.contended.total%2Ccluster.protostats.jobd.total%2Cnode.cpu.throttling%2Ccluster.protostats.smb2%2Cnode.clientstats.active.papi%2Cnode.clientstats.connected.http%2Cifs.bytes.in.rate%2Cnode.clientstats.connected.nfs%2Ccluster.protostats.papi%2Cnode.memory.free%2Cnode.ifs.heat.lookup.total&devid=all&substr=False&timeout=60&degraded=True&expand_clientid=False
2017-05-01 16:47:47,087:urllib3.connectionpool:WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x4cfee50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.open.files%2Ccluster.protostats.siq.total%2Cnode.clientstats.connected.ftp%2Ccluster.net.ext.bytes.out.rate%2Cnode.clientstats.active.smb1%2Cnode.clientstats.active.smb2%2Ccluster.net.ext.errors.in.rate%2Ccluster.protostats.irp.total%2Cifs.ops.out.rate%2Cnode.clientstats.connected.cifs%2Ccluster.cpu.idle.avg%2Ccluster.net.ext.packets.out.rate%2Cnode.ifs.heat.rename.total%2Cifs.bytes.out.rate%2Ccluster.protostats.irp%2Cnode.load.5min%2Cnode.memory.used%2Ccluster.protostats.nlm.total%2Cnode.clientstats.active.hdfs%2Cnode.clientstats.connected.nlm%2Cifs.bytes.free%2Ccluster.protostats.nfs4.total%2Cifs.percent.free%2Ccluster.protostats.nlm%2Cnode.ifs.heat.read.total%2Cnode.clientstats.active.nlm%2Ccluster.health%2Ccluster.disk.bytes.out.rate%2Ccluster.disk.bytes.in.rate%2Ccluster.protostats.nfs%2Ccluster.protostats.papi.total%2Cifs.bytes.used%2Ccluster.node.count.all%2Ccluster.protostats.smb2.total%2Ccluster.protostats.jobd%2Ccluster.net.ext.packets.in.rate%2Ccluster.protostats.lsass_out%2Ccluster.protostats.hdfs.total%2Cnode.clientstats.connected.hdfs%2Cnode.clientstats.active.nfs3%2Ccluster.protostats.lsass_in%2Cnode.clientstats.active.nfs4%2Cnode.clientstats.active.ftp%2Cnode.ifs.heat.deadlocked.total%2Ccluster.protostats.nfs4%2Cnode.clientstats.connected.papi%2Cnode.ifs.cache%2Ccluster.protostats.lsass_in.total%2Cifs.bytes.total%2Cnode.ifs.heat.lock.total%2Ccluster.net.ext.errors.out.rate%2Cnode.clientstats.connected.siq%2Cnode.clientstats.active.lsass_out%2Cifs.ops.in.rate%2Cnode.clientstats.active.cifs%2Cnode.ifs.heat.link.total%2Cnode.ifs.heat.setattr.total%2Cnode.load.15min%2Ccluster.protostats.cifs%2Cifs.percent.avail%2Ccluster.net.ext.bytes.in.rate%2Ccluster.protostats.nfs.total%2Cnode.ifs.heat.getattr.total%2Cnode.ifs.heat.unlink.total%2Ccluster.protostats.http%2Cnode.ifs.heat.blocked.total%2Cnode.clientstats.active.jobd%2Ccluster.protostats.hdfs%2Ccluster.protostats.cifs.total%2Ccluster.protostats.ftp%2Cnode.clientstats.active.http%2Cnode.load.1min%2Ccluster.node.count.down%2Ccluster.cpu.intr.avg%2Cifs.percent.used%2Cnode.ifs.heat.write.total%2Ccluster.disk.xfers.in.rate%2Cifs.bytes.avail%2Cnode.memory.cache%2Ccluster.cpu.user.avg%2Ccluster.disk.xfers.out.rate%2Ccluster.protostats.http.total%2Ccluster.disk.xfers.rate%2Cnode.clientstats.active.siq%2Ccluster.protostats.siq%2Ccluster.protostats.ftp.total%2Ccluster.cpu.sys.avg%2Cnode.ifs.heat.contended.total%2Ccluster.protostats.jobd.total%2Cnode.cpu.throttling%2Ccluster.protostats.smb2%2Cnode.clientstats.active.papi%2Cnode.clientstats.connected.http%2Cifs.bytes.in.rate%2Cnode.clientstats.connected.nfs%2Ccluster.protostats.papi%2Cnode.memory.free%2Cnode.ifs.heat.lookup.total&devid=all&substr=False&timeout=60&degraded=True&expand_clientid=False
2017-05-01 16:47:47,088:daemons.startstop.simple:ERROR: Uncaught exception in the daemon run() method.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/daemons/startstop/simple.py", line 43, in start
    self.run()
  File "/root/isilon_data_insights_connector/isi_data_insights_daemon.py", line 148, in run
    self._query_and_process_stats(time.time())
  File "/root/isilon_data_insights_connector/isi_data_insights_daemon.py", line 215, in _query_and_process_stats
    results = stats_client.query_stats(stats)
  File "/root/isilon_data_insights_connector/isi_stats_client.py", line 80, in query_stats
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/apis/statistics_api.py", line 139, in get_statistics_current
    callback=params.get('callback'))
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 339, in call_api
    response_type, auth_settings, callback)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 166, in __call_api
    post_params=post_params, body=body)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 359, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/rest.py", line 184, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/rest.py", line 161, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 313, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='nfs-isi2.nygenome.org', port=8080): Max retries exceeded with url: /platform/1/statistics/current?keys=cluster.protostats.lsass_out.total%2Cnode.open.files%2Ccluster.protostats.siq.total%2Cnode.clientstats.connected.ftp%2Ccluster.net.ext.bytes.out.rate%2Cnode.clientstats.active.smb1%2Cnode.clientstats.active.smb2%2Ccluster.net.ext.errors.in.rate%2Ccluster.protostats.irp.total%2Cifs.ops.out.rate%2Cnode.clientstats.connected.cifs%2Ccluster.cpu.idle.avg%2Ccluster.net.ext.packets.out.rate%2Cnode.ifs.heat.rename.total%2Cifs.bytes.out.rate%2Ccluster.protostats.irp%2Cnode.load.5min%2Cnode.memory.used%2Ccluster.protostats.nlm.total%2Cnode.clientstats.active.hdfs%2Cnode.clientstats.connected.nlm%2Cifs.bytes.free%2Ccluster.protostats.nfs4.total%2Cifs.percent.free%2Ccluster.protostats.nlm%2Cnode.ifs.heat.read.total%2Cnode.clientstats.active.nlm%2Ccluster.health%2Ccluster.disk.bytes.out.rate%2Ccluster.disk.bytes.in.rate%2Ccluster.protostats.nfs%2Ccluster.protostats.papi.total%2Cifs.bytes.used%2Ccluster.node.count.all%2Ccluster.protostats.smb2.total%2Ccluster.protostats.jobd%2Ccluster.net.ext.packets.in.rate%2Ccluster.protostats.lsass_out%2Ccluster.protostats.hdfs.total%2Cnode.clientstats.connected.hdfs%2Cnode.clientstats.active.nfs3%2Ccluster.protostats.lsass_in%2Cnode.clientstats.active.nfs4%2Cnode.clientstats.active.ftp%2Cnode.ifs.heat.deadlocked.total%2Ccluster.protostats.nfs4%2Cnode.clientstats.connected.papi%2Cnode.ifs.cache%2Ccluster.protostats.lsass_in.total%2Cifs.bytes.total%2Cnode.ifs.heat.lock.total%2Ccluster.net.ext.errors.out.rate%2Cnode.clientstats.connected.siq%2Cnode.clientstats.active.lsass_out%2Cifs.ops.in.rate%2Cnode.clientstats.active.cifs%2Cnode.ifs.heat.link.total%2Cnode.ifs.heat.setattr.total%2Cnode.load.15min%2Ccluster.protostats.cifs%2Cifs.percent.avail%2Ccluster.net.ext.bytes.in.rate%2Ccluster.protostats.nfs.total%2Cnode.ifs.heat.getattr.total%2Cnode.ifs.heat.unlink.total%2Ccluster.protostats.http%2Cnode.ifs.heat.blocked.total%2Cnode.clientstats.active.jobd%2Ccluster.protostats.hdfs%2Ccluster.protostats.cifs.total%2Ccluster.protostats.ftp%2Cnode.clientstats.active.http%2Cnode.load.1min%2Ccluster.node.count.down%2Ccluster.cpu.intr.avg%2Cifs.percent.used%2Cnode.ifs.heat.write.total%2Ccluster.disk.xfers.in.rate%2Cifs.bytes.avail%2Cnode.memory.cache%2Ccluster.cpu.user.avg%2Ccluster.disk.xfers.out.rate%2Ccluster.protostats.http.total%2Ccluster.disk.xfers.rate%2Cnode.clientstats.active.siq%2Ccluster.protostats.siq%2Ccluster.protostats.ftp.total%2Ccluster.cpu.sys.avg%2Cnode.ifs.heat.contended.total%2Ccluster.protostats.jobd.total%2Cnode.cpu.throttling%2Ccluster.protostats.smb2%2Cnode.clientstats.active.papi%2Cnode.clientstats.connected.http%2Cifs.bytes.in.rate%2Cnode.clientstats.connected.nfs%2Ccluster.protostats.papi%2Cnode.memory.free%2Cnode.ifs.heat.lookup.total&devid=all&substr=False&timeout=60&degraded=True&expand_clientid=False (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x4cfed50>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-05-01 16:47:47,090:isi_data_insights_daemon:INFO: Stoppping.`

**Comment by lbanz** [comment]
Ok fixed. One of the isilon cluster wasn't playing ball with the roundrobin dns. I changed it to using the Smart connect IP and it worked.
