### ISSUE TITLE
Missing result, communication with remote resource timed out

### ISSUE THREAD

**Issue by eschek87** [Isilon/isilon_data_insights_connector#44]
I updated/replaced the files influxdb_plugin.py, isi_data_insights_d.py, isi_data_insights_daemon.py and requirements.txt. And the I have done pip install -r requirements.txt and now I see the following errors for one of our clusters:

2017-08-29 12:26:05,592:isi_data_insights_daemon:WARNING: Query for stat: 'node.ifs.cache' on 'SRZ-ISILON', returned error: 'Missing result, communication with remote resource timed out'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 694, in _query_and_process_stats1
    cluster.name, results, derived_stats_processors)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 744, in _process_stats_with_derived_stats
    derived_stat = composite_stat.compute_derived_stat()
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 205, in compute_derived_stat
    self._operation(self._selected_stat_values))
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 118, in _create_derived_stat
    self._get_timestamp_avg(devid), error)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 128, in _get_timestamp_avg
    return long(tot / tot_count)
ZeroDivisionError: integer division or modulo by zero
Tue Aug 29 12:26:57 2017 <Greenlet at 0x7fc7a4ca6f50: <bound method IsiDataInsightsDaemon._query_and_process_stats1 of <isi_data_insights_daemon.IsiDataInsightsDaemon object at 0x7fc7a56e5690>>(PRZ-ISILON, set(['cluster.protostats.lsass_out.total', 'node.c, [<isi_data_insights_daemon.ClusterCompositeStatCom, [<isi_data_insights_daemon.EquationStatComputer ob, [<isi_data_insights_daemon.PercentChangeStatComput, [<isi_data_insights_daemon.EquationStatComputer ob)> failed with ZeroDivisionError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 694, in _query_and_process_stats1
    cluster.name, results, derived_stats_processors)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 744, in _process_stats_with_derived_stats
    derived_stat = composite_stat.compute_derived_stat()
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 205, in compute_derived_stat
    self._operation(self._selected_stat_values))
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 118, in _create_derived_stat
    self._get_timestamp_avg(devid), error)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_daemon.py", line 128, in _get_timestamp_avg
    return long(tot / tot_count)
ZeroDivisionError: integer division or modulo by zero
Tue Aug 29 12:29:57 2017 <Greenlet at 0x7fc7a4ca6eb0: <bound method IsiDataInsightsDaemon._query_and_process_stats1 of <isi_data_insights_daemon.IsiDataInsightsDaemon object at 0x7fc7a56e5690>>(PRZ-ISILON, set(['cluster.protostats.lsass_out.total', 'node.c, [<isi_data_insights_daemon.ClusterCompositeStatCom, [<isi_data_insights_daemon.EquationStatComputer ob, [<isi_data_insights_daemon.PercentChangeStatComput, [<isi_data_insights_daemon.EquationStatComputer ob)> failed with ZeroDivisionError

**Comment by apecoraro** [comment]
The divide by zero error should be fixed by the latest commit (https://github.com/Isilon/isilon_data_insights_connector/commit/5fc24075bbb5d30871dfc5df66c7b1a6f827348e). As far as why your cluster is not responding to queries of the /platform/1/statistics/current endpoint, that is something you might have to sort out by getting in touch with support.
