### ISSUE TITLE
This tool is not compatible with isi-sdk 0.2.x

### ISSUE THREAD

**Issue by kaoet** [Isilon/isilon_data_insights_connector#50]
Run this script with `isi-sdk-7-2` produce:
```
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 71, in <module>
    main()
  File "./isi_data_insights_d.py", line 48, in main
    configure_via_file(daemon, args, config_file)
  File "/home/infra/isilon_data_insights_connector/isi_data_insights_config.py", line 668, in configure_via_file
    config_file, stat_group, global_cluster_list)
  File "/home/infra/isilon_data_insights_connector/isi_data_insights_config.py", line 298, in _configure_stat_groups_via_file
    cluster_configs = _build_cluster_configs(cluster_list)
  File "/home/infra/isilon_data_insights_connector/isi_data_insights_config.py", line 165, in _build_cluster_configs
    cluster, username, password, verify_ssl)
  File "/home/infra/isilon_data_insights_connector/isi_sdk_utils.py", line 57, in configure
    _detect_host_version(host_url, username, password, verify_ssl)
  File "/home/infra/isilon_data_insights_connector/isi_sdk_utils.py", line 89, in _detect_host_version
    api_client = api_client_class(host, verify_ssl)
  File "/home/infra/isilon_data_insights_connector/isi_api_client_7_2.py", line 21, in __init__
    super(IsiApiClient_7_2, self).__init__(host=host)
TypeError: __init__() got an unexpected keyword argument 'host'
Exception AttributeError: "'IsiApiClient_7_2' object has no attribute 'pool'" in <bound method IsiApiClient_7_2.__del__ of <isi_api_client_7_2.IsiApiClient_7_2 object at 0x7fca1afdb8d0>> ignored
```

Workaround: Change `requirements.txt` like
```
isi_sdk_8_0 >= 0.1.2, < 0.2.0
isi_sdk_7_2 >= 0.1.2, < 0.2.0
```

**Comment by tomboxme** [comment]
Aha, that fixed it. Thank you!

**Comment by tux1337** [comment]
I can also confirm, that this fixed the issue.

**Comment by tenortim** [comment]
I still need to update the data insights code to work with the updated SDK.
