### ISSUE TITLE
Python stack trace

### ISSUE THREAD

**Issue by ghost** [Isilon/isilon_data_insights_connector#51]
Hi there guys,

Trying to get this running on our cluster running 8.1.0 but getting the following;

```
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 65, in <module>
    main()
  File "./isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 668, in configure_via_file
    config_file, stat_group, global_cluster_list)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 298, in _configure_stat_groups_via_file
    cluster_configs = _build_cluster_configs(cluster_list)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 165, in _build_cluster_configs
    cluster, username, password, verify_ssl)
  File "/opt/isilon_data_insights_connector/isi_sdk_utils.py", line 56, in configure
    _detect_host_version(host_url, username, password, verify_ssl)
  File "/opt/isilon_data_insights_connector/isi_sdk_utils.py", line 87, in _detect_host_version
    api_client = api_client_class(host, verify_ssl)
  File "/opt/isilon_data_insights_connector/isi_api_client_7_2.py", line 21, in __init__
    super(IsiApiClient_7_2, self).__init__(host=host)
TypeError: __init__() got an unexpected keyword argument 'host'
Exception AttributeError: "'IsiApiClient_7_2' object has no attribute 'pool'" in <bound method IsiApiClient_7_2.__del__ of <isi_api_client_7_2.IsiApiClient_7_2 object at 0x4fce190>> ignored
```

Any ideas? Running off a centos 7.4 VM

**Comment by dmtucker** [comment]
This looks like #50. What SDK version do you have?

**Comment by tenortim** [comment]
@ghost were you able to get this working based off the changes in #50?

**Comment by tenortim** [comment]
Since #50 is now fixed, I'm closing this as fixed.
