### ISSUE TITLE
Can't seem to get this running

### ISSUE THREAD

**Issue by tomboxme** [Isilon/isilon_data_insights_connector#6]
What version of python are you developing with ?

I'm having problems with 2.6, 2.7 & 3

    ./isi_data_insights_d.py start
  File "./isi_data_insights_d.py", line 44
    print "Restarting daemon with pid " + str(daemon.pid)
                                      ^
    SyntaxError: invalid syntax
    (.venv) [root@python3 isilon_data_insights_connector-master]# python isi_data_insights_
    python: can't open file 'isi_data_insights_': [Errno 2] No such file or directory
    (.venv) [root@python3 isilon_data_insights_connector-master]# python isi_data_insights_d.py 
     File "isi_data_insights_d.py", line 44
      print "Restarting daemon with pid " + str(daemon.pid)
                                      ^
    SyntaxError: invalid syntax

**Comment by dmtucker** [comment]
@tomboxme `./isi_data_insights_d.py` uses Python 2 `print`s. In Python 3, `print` is a function (which is a backwards incompatible-change). So you'll need to use 2.x. Unfortunately, I'm not sure exactly which version this was tested with...

What problems are you seeing with 2.6/2.7?

**Comment by tomboxme** [comment]
I'm running 2.6.6 

    python -V
    Python 2.6.6

and getting the following errors. 

     /isi_data_insights_d.py start
    Traceback (most recent call last):
    File "./isi_data_insights_d.py", line 4, in <module>
    from isi_data_insights_config import parse_cli, \
    File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 15, in      
    <module>
    import isi_sdk_utils
    File "/opt/isilon_data_insights_connector-master/isi_sdk_utils.py", line 6, in <module>
    import isi_sdk_8_0
    File "/opt/isilon_data_insights_connector-master/.venv/lib/python2.6/site-  
    packages/isi_sdk_8_0/__init__.py", line 761, in <module>
    from .apis.antivirus_api import AntivirusApi
   File "/opt/isilon_data_insights_connector-master/.venv/lib/python2.6/site-  
   packages/isi_sdk_8_0/apis/__init__.py", line 4, in <module>
   from .antivirus_api import AntivirusApi
   File "/opt/isilon_data_insights_connector-master/.venv/lib/python2.6/site-packages/isi_sdk_8_0/apis/antivirus_api.py", line 30, in <module>
    from ..api_client import ApiClient
  File "/opt/isilon_data_insights_connector-master/.venv/lib/python2.6/site-  
    packages/isi_sdk_8_0/api_client.py", line 128
    for k, v in iteritems(query_params)}
      ^
    SyntaxError: invalid syntax

**Comment by tomboxme** [comment]
Aha, figured it out. Was doing something stupid on my end 👎
