### ISSUE TITLE
isi_data_insights_d.py start problem

### ISSUE THREAD

**Issue by argstarfire** [Isilon/isilon_data_insights_connector#61]
Hi, I'm sorry my English is very bad.
My problem is that when I start ./isi_data_insights_d.py start I get the following error:

Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 65, in <module>
    main()
  File "./isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 627, in configure_via_file
    args.stats_processor, args.processor_args)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 560, in _configure_stats_processor
    daemon.set_stats_processor(processor, arg_list)
  File "/opt/isilon_data_insights_connector/isi_data_insights_daemon.py", line 484, in set_stats_processor
    self._stats_processor.start(self._stats_processor_args)
  File "/opt/isilon_data_insights_connector/influxdb_plugin.py", line 73, in start
    str(influxdb_port), influxdb_name, str(exc))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 7364: ordinal not in range(128)

I appreciate the help

**Comment by fr3man1** [comment]
have you ammended your isi_data_insights.cfg through windows text editor? if so, could you try aplying dos2unix on that file ?

**Comment by argstarfire** [comment]
Hi,

It was not modified, it was installed directly in a Redhat 7.6. I was able to solve the problem
It was still necessary to open the ports of the 8086 firewall of influxdb and also to install a library of python (monkey).
Thank you very much for your collaboration. 
Sorry for my English. Thanks.

**Comment by tenortim** [comment]
Closing based on the comment that @argstarfire was able to solve the problem.
