### ISSUE TITLE
OneFS 8.2.0 Supprt

### ISSUE THREAD

**Issue by Tomster1** [Isilon/isilon_data_insights_connector#67]
It´s not possible to connect to a 8.2.0 cluster. Following error message appears. Please add support for most current OneFS releases. Thanks

Computing update intervals for stat group: node_load_stats.
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 65, in <module>
    main()
  File "./isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 668, in configure_via_file
    config_file, stat_group, global_cluster_list)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 345, in _configure_stat_groups_via_file
    update_intervals)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 236, in _compute_stat_group_update_intervals
    stats_metadata = _query_stats_metadata(cluster, stat_names)
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 225, in _query_stats_metadata
    return isi_stats_client.get_stats_metadata(stat_names)
  File "/opt/isilon_data_insights_connector-master/isi_stats_client.py", line 126, in get_stats_metadata
    return self._get_metadata_direct(stats)
  File "/opt/isilon_data_insights_connector-master/isi_stats_client.py", line 197, in _get_metadata_direct
    metadata = self.get_stat_metadata(stat)
  File "/opt/isilon_data_insights_connector-master/isi_stats_client.py", line 138, in get_stat_metadata
    statistics_key_id=stat)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/apis/statistics_api.py", line 325, in get_statistics_key
    callback=params.get('callback'))
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 339, in call_api
    response_type, auth_settings, callback)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 166, in __call_api
    post_params=post_params, body=body)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/api_client.py", line 359, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/rest.py", line 184, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/isi_sdk_8_0/rest.py", line 177, in request
    raise ApiException(http_resp=r)
isi_sdk_8_0.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 27 May 2019 12:02:21 GMT', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json', 'Allow': 'GET, HEAD', 'Server': 'Apache'})
HTTP response body:
{
"errors" :
[

{
"code" : "AEC_NOT_FOUND",
"message" : "Key node.memory.cache not found"
}
]
}

**Comment by fr3man1** [comment]
Hello,
Did you try removing node.memory.cache from the running configuration? I have spotted a case when some metric keys where throwing unhandled exception directly from onefs api. Maybe now a key got completely removed from api. 
Best regards

**Comment by Tomster1** [comment]
Hi,
removing the key from the config fixes the issue. Thanks.

**Comment by lukeskaivolker** [comment]
As well I suggest to use new SDK fo 8.2 https://community.emc.com/docs/DOC-48273

**Comment by tenortim** [comment]
Closing as a dup of #66
